FROM alpine-jdk17:latest

VOLUME /tmp

ARG JAR_FILE
COPY ${JAR_FILE} service.jar

ENTRYPOINT ["java","-XX:+UseG1GC","--add-opens=java.base/sun.reflect.annotation=ALL-UNNAMED","--add-opens=java.base/sun.security.pkcs=ALL-UNNAMED","--add-opens=java.base/sun.security.util=ALL-UNNAMED","--add-opens=java.base/sun.security.x509=ALL-UNNAMED","-XX:+UseStringDeduplication", "-XX:ParallelGCThreads=10", "-XX:ConcGCThreads=3", "-XX:InitiatingHeapOccupancyPercent=40", "-XX:+UseContainerSupport", "-XX:MinRAMPercentage=80.0", "-XX:MaxRAMPercentage=80.0", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=distrib", "-jar", "/service.jar"]