dependencies {
  api(commons.codec)
  api(commons.io)
  api(libs.fasterxml.uuid)
  api(libs.guava)

  api('org.springframework.boot:spring-boot-starter-aspectj')
  api('org.springframework.kafka:spring-kafka')

  api project(':jprime-common-api')

  testImplementation project(":jprime-test")
}

bootJar {
	enabled = false
}

jar {
	enabled = true
}