# Jwt
[versions]
jjwtVersion = "0.12.6"

[libraries]
jjwt-api = { module="io.jsonwebtoken:jjwt-api", version.ref="jjwtVersion" }
jjwt-impl = { module="io.jsonwebtoken:jjwt-impl", version.ref="jjwtVersion" }
jjwt-jackson = { module="io.jsonwebtoken:jjwt-jackson", version.ref="jjwtVersion" }

[bundles]
jjwt-v1 = ['jjwt-api', 'jjwt-impl', 'jjwt-jackson']