# Commons
[versions]
commonsCodecVersion = "1.17.1"
commonsCollections4Version = "4.4"
commonsIoVersion = "2.16.1"
commonsLang3Version = "3.17.0"
commonsValidatorVersion = "1.8.0"
monetaCoreVersion = "1.4.4"
tikaCoreVersion = "2.9.1"
guavaVersion = "33.3.1-jre"
fasterxmlUuidVersion = "5.1.0"
apacheHttpClientVersion = "5.4.1"
commonsNetVersion = "3.9.0"
fastjsonVersion = "2.0.53"
jaxbApiVersionOld = "2.3.1"
jaxbRuntimeVersionOld = "2.3.8"
jaxbApiVersion = "4.0.2"
jaxbRuntimeVersion = "4.0.5"
jakartaWsApiVersion = "4.0.2"
jaxwsVersion = "4.0.2"
jakartaActivationVersion = "2.1.3"
zxingVersion = "3.5.1" # Генерация штрих кодов и QR кодов

[libraries]
codec = { module="commons-codec:commons-codec", version.ref="commonsCodecVersion" }
io = { module="commons-io:commons-io", version.ref="commonsIoVersion" }
collections4 = { module="org.apache.commons:commons-collections4", version.ref="commonsCollections4Version" }
lang3 = { module="org.apache.commons:commons-lang3", version.ref="commonsLang3Version" }
validator = { module="commons-validator:commons-validator", version.ref="commonsValidatorVersion" }
moneta-core = { module="org.javamoney.moneta:moneta-core", version.ref="monetaCoreVersion" }
tika-core = { module="org.apache.tika:tika-core", version.ref="tikaCoreVersion" }
guava = { module="com.google.guava:guava", version.ref="guavaVersion" }
fasterxml-uuid = { module="com.fasterxml.uuid:java-uuid-generator", version.ref="fasterxmlUuidVersion" }
apache-httpclient = { module="org.apache.httpcomponents.client5:httpclient5", version.ref="apacheHttpClientVersion" }
net = { module="commons-net:commons-net", version.ref="commonsNetVersion" }
fastjson = { module="com.alibaba.fastjson2:fastjson2", version.ref="fastjsonVersion" }
jaxb-api = { module="jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxbApiVersion" }
jaxb-runtime = { module="org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxbRuntimeVersion" }
jakarta-ws-api = { module="jakarta.xml.ws:jakarta.xml.ws-api", version.ref = "jakartaWsApiVersion" }
jaxws-rt = { module="com.sun.xml.ws:rt", version.ref = "jaxwsVersion" }
jakarta-activation = { module="jakarta.activation:jakarta.activation-api", version.ref = "jakartaActivationVersion" }
zxing-core = { module="com.google.zxing:core", version.ref = "zxingVersion" }
zxing-javase = { module="com.google.zxing:javase", version.ref = "zxingVersion" }

[bundles]
jaxb = ['jaxb-api', 'jaxb-runtime']
jaxws = ['jakarta-ws-api', 'jaxws-rt', 'jakarta-activation']
zxing = ['zxing-core', 'zxing-javase']
