[versions]
# jackson
jacksonAnnotationsVersion = "2.13.5"
jacksonDataformatXmlVersion = "2.13.5"
jacksonDatatypeJsr310Version = "2.13.5"
# java-generator
javapoetVersion = "1.13.0"
# file-converter
jodconverterLocalVersion = "4.4.6"
# http-parser
nioMultipartParserVersion = "1.1.0"
# sshj
sshjVersion = "0.35.0"
# lombok
lombokVersion = "1.18.26"
lombokPluginVersion = "6.6.1"

[libraries]
jackson-annotations = { module="com.fasterxml.jackson.core:jackson-annotations", version.ref="jacksonAnnotationsVersion" }
jackson-dataformat-xml = { module="com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref="jacksonDataformatXmlVersion" }
jackson-datatype-jsr310 = { module="com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref="jacksonDatatypeJsr310Version" }
javapoet = { module="com.squareup:javapoet", version.ref="javapoetVersion" }
jodconverter-local = { module="org.jodconverter:jodconverter-local", version.ref="jodconverterLocalVersion" }
nio-multipart-parser = { module="org.synchronoss.cloud:nio-multipart-parser", version.ref="nioMultipartParserVersion" }
sshj ={ module="com.hierynomus:sshj", version.ref="sshjVersion" }
lombok ={ module="org.projectlombok:lombok", version.ref="lombokVersion" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref="lombokPluginVersion" }

[bundles]
jackson-v1 = ['jackson-dataformat-xml', 'jackson-datatype-jsr310']