# Отчёты
[versions]
jasperreportsVersion = "6.21.3"
jasperreportsFontsVersion = "6.21.3"
jasperreportsFontsLiberationVersion = "2.1.2"
jmixVersion = "2.3.0" # Jmix yarg генератор отчетов
openpdfVersion = "2.0.1"
jsonSimpleVersion = "1.1.1"
olap4JVersion = "1.2.0"
poiVersion = "5.3.0" # Работа с XLS. Повышать надо вместе с jmixVersion

[libraries]
jasperreports = { module="net.sf.jasperreports:jasperreports", version.ref="jasperreportsVersion" }
jasperreports-fonts = { module="net.sf.jasperreports:jasperreports-fonts", version.ref="jasperreportsFontsVersion" }
jasperreports-fonts-liberation = { module="com.mpobjects.jasperreports.font:jasperreports-fonts-liberation", version.ref="jasperreportsFontsLiberationVersion" }
openpdf = { module="com.github.librepdf:openpdf", version.ref = "openpdfVersion" }
json-simple = { module="com.googlecode.json-simple:json-simple", version.ref="jsonSimpleVersion" }
jmix = { module="io.jmix.reports:jmix-reports", version.ref="jmixVersion" }
olap4j = { module="org.olap4j:olap4j", version.ref="olap4JVersion" }
poi = { module="org.apache.poi:poi", version.ref="poiVersion" }
poi-ooxml = { module="org.apache.poi:poi-ooxml", version.ref="poiVersion" }

[bundles]
jasperreports-v1 = ['jasperreports', 'jasperreports-fonts', 'jasperreports-fonts-liberation']