# GeoTools
[versions]
geotoolsVersion = "33.1"
orgLocationtechVersion = "1.20.0"
postgisJdbcVersion = "2025.1.1"
querydslSqlVersion = "5.1.0"

[libraries]
gt-shapefile = { module = "org.geotools:gt-shapefile", version.ref = "geotoolsVersion" }
gt-epsg-hsql = { module = "org.geotools:gt-epsg-hsql", version.ref = "geotoolsVersion" }
org-locationtech-jts-io-common = { module = "org.locationtech.jts.io:jts-io-common", version.ref = "orgLocationtechVersion" }
postgis-jdbc = { module = "net.postgis:postgis-jdbc", version.ref = "postgisJdbcVersion" }
querydsl-sql-spatial = { module = "com.querydsl:querydsl-sql-spatial", version.ref = "querydslSqlVersion" }

[bundles]
geotools = ['gt-shapefile', 'gt-epsg-hsql', 'org-locationtech-jts-io-common']