[versions]
# Spring
springBootVersion = "3.2.2"
springCloudVersion = "2023.0.0"
securityOauth2AuthVersion = "1.2.1"
dependencyManagement = "1.1.4"
springBootAdminStarterServer = "3.2.1"

[libraries]
security-oauth2-authorization-server = { module = "org.springframework.security:spring-security-oauth2-authorization-server", version.ref = "securityOauth2AuthVersion"}
boot-admin-starter-server = { module = "de.codecentric:spring-boot-admin-starter-server", version.ref = "springBootAdminStarterServer"}

[plugins]
boot = { id = "org.springframework.boot", version.ref="springBootVersion" }
dependency-management = { id = "io.spring.dependency-management", version.ref= "dependencyManagement" }