[versions]
# Spring
springBootVersion = "2.7.11"
springCloudVersion = "2021.0.7"
dependencyManagement = "1.1.0"
springBootAdminStarterServer = "2.7.10"

[libraries]
boot-admin-starter-server = { module = "de.codecentric:spring-boot-admin-starter-server", version.ref = "springBootAdminStarterServer"}

[plugins]
boot = { id = "org.springframework.boot", version.ref="springBootVersion" }
dependency-management = { id = "io.spring.dependency-management", version.ref= "dependencyManagement" }