# Базы данных
[versions]
postgresqlVersion = "42.5.0"
r2dbcPostgresqlVersion = { strictly = "0.9.0.RELEASE" }
mssqlJdbcVersion = "10.2.1.jre8"
clickhouseJdbcVersion = "0.3.1"
jtdsVersion = "1.3.1"
querydslSqlVersion = "5.0.0"
minioVersion = "8.4.6"

[libraries]
postgresql = { module="org.postgresql:postgresql", version.ref="postgresqlVersion" }
mssql = { module="com.microsoft.sqlserver:mssql-jdbc", version.ref="mssqlJdbcVersion" }
clickhouse = { module="ru.yandex.clickhouse:clickhouse-jdbc", version.ref="clickhouseJdbcVersion" }
jtds = { module="net.sourceforge.jtds:jtds", version.ref="jtdsVersion" }
querydsl-sql = { module="com.querydsl:querydsl-sql", version.ref="querydslSqlVersion" }
minio = { module="io.minio:minio", version.ref="minioVersion" }

r2dbc-pool = { module="io.r2dbc:r2dbc-pool", version.ref="r2dbcPostgresqlVersion" }
r2dbc-proxy = { module="io.r2dbc:r2dbc-proxy", version.ref="r2dbcPostgresqlVersion" }
r2dbc-spi = { module="io.r2dbc:r2dbc-spi", version.ref="r2dbcPostgresqlVersion" }
r2dbc-spi-parent = { module="io.r2dbc:r2dbc-spi-parent", version.ref="r2dbcPostgresqlVersion" }
r2dbc-postgresql = { module="org.postgresql:r2dbc-postgresql", version.ref="r2dbcPostgresqlVersion" }

[bundles]
v1 = ['postgresql', 'mssql', 'clickhouse', 'jtds']
r2dbc = ['r2dbc-pool', 'r2dbc-proxy', 'r2dbc-spi', 'r2dbc-spi-parent', 'r2dbc-postgresql']