# Tests
[versions]
testContainersVersion = "1.21.3"
reactorTestVersion = "3.7.8"

[libraries]
testcontainers-postgresql = { module="org.testcontainers:postgresql", version.ref="testContainersVersion" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testContainersVersion" }
projectreactor-reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactorTestVersion" }

[bundles]
testcontainers-v1 = ['testcontainers-postgresql', 'testcontainers-junit-jupiter', 'projectreactor-reactor-test']
